### ISSUE TITLE
different results between phagcn2 and phabox

### ISSUE THREAD

**Issue by mengyuan-JI** [KennthShang/PhaBOX#16]
Hi，I use phagcn2 and phabox to do the classification for the same fasta files, but it shows me very different result，Im not sure which one can be trust

**Comment by KennthShang** [comment]
Hi there,

PhaGCN2 is designed for all viruses. PhaBOX will only predict the bacteriophages.

Best,
Jiayu

**Comment by mengyuan-JI** [comment]
thank you for answering! can I use PhaBOX also for archaea phages?

**Comment by mengyuan-JI** [comment]
I mainly want to make predictions about phages in soil systems, but for example for the contigs "DP_phages_080", phabox gives me: Chaseviridae,1.0 and phagcn2 givesme: Autographiviridae_like. Both of them are bacteria virus.

**Comment by KennthShang** [comment]
In this case, you should use phabox's prediction. Since I am not correspondence to maintaining PhaGCN2, I am not sure whether they have updated the ICTV taxonomy. But in the case of PhaBOX can give a result, it should have the highest confidence, since we have updated the program regularly.

Best,
Jiayu

**Comment by mengyuan-JI** [comment]
OK，thanks a lot

**Comment by KennthShang** [comment]
Hi there,

The PhaBOX is upgraded to a 2.0 version with more powerful usage. Besides, it can handle all kinds of viruses now. Feel free to check!

Best,
Jiayu
