### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by TKsh6** [KennthShang/PhaBOX#2]
hello,
I had met a problem, when I run this command,
```
python main.py --contigs /beegfs/home/syl/task_meta/BW_riceclarkia_free/MGB_assembly_5_quality_control/MGB_assembly_2_drep_res/newid_genomes/CMIBWM2_mixbin.190.fa \
--threads 8 --len 3000 --rootpth temp_rootpth --out temp_out \
--dbdir /beegfs/home/syl/software/phabox/PhaBOX-main/database \
--parampth /beegfs/home/syl/software/phabox/PhaBOX-main/parameters
```
I met this problem,
`/bin/bash: line 4: 158069 Illegal instruction     (core dumped) python main.py --contigs /bee  gfs/home/syl/task_meta/BW_riceclarkia_free/MGB_assembly_5_quality_control/MGB_assembly_2_drep  _res/newid_genomes/CMIBWM2_mixbin.190.fa --threads 8 --len 3000 --rootpth temp_rootpth --out   temp_out --dbdir /beegfs/home/syl/software/phabox/PhaBOX-main/database --parampth /beegfs/hom  e/syl/software/phabox/PhaBOX-main/parameters`
So how can I do to solve this?
yours tk

**Comment by KennthShang** [comment]
Hi,

I did not meet this problem before but It must be a problem caused by your device/system.


Below are the answers I found using google:

1. If you are using virtual machine, make sure your system allow 'avx' instruction set.

2. Try to add "export OPENBLAS_CORETYPE=ARMV8" to your env path.

Best,
Jiayu

**Comment by TKsh6** [comment]
Thank you, I have made it.

yours

**Comment by KennthShang** [comment]
Good to know.
