### ISSUE TITLE
installing phabox2 in developer mode

### ISSUE THREAD

**Issue by myfriendking** [KennthShang/PhaBOX#29]
Dear Developer,

When I try to install PhaBox2 using the command “mamba create -p /soft/PhaBOX2 jyshang2::phabox=2.0 -c pytorch -c huggingface -c bioconda -c conda-forge”, I always receive the message:

PhaBox2_install.sh: line 2: 144734 Killed mamba create -p /soft/PhaBOX2 jyshang2::phabox=2.0 -c pytorch -c huggingface -c bioconda -c conda-forge
I found that it might be due to the jyshang2 channel. The content before the "Killed" message is:
info libmamba Writing SOLV file 'd17dcf2e.solv'
info libmamba Parsing MatchSpec jyshang2::phabox=2.0
info libmamba Parsing MatchSpec jyshang2::phabox=2.0
or (without adding -c jyshang2):
info libmamba Parsing MatchSpec phabox=2.0
info libmamba Parsing MatchSpec phabox=2.0
info libmamba Adding job: phabox =2.0*
How can I successfully install it? Are there any other recommended installation methods?

Additionally, I am located in mainland China. Looking forward to your reply.

**Comment by KennthShang** [comment]
Hi there,

First of all, please try conda rather than mamba as we did not test the installation using mamba.

If you still cannot install the program, then please try the following commands:
```
git clone https://github.com/KennthShang/PhaBOX.git
cd PhaBOX
conda env create -f  phabox2.yml -n phabox2 -y

conda activate phabox2
python -m pip install . -vv

# test
phabox2 --help
```

If the command above works, you can run it in anywhere

Since we are still upgrading the program, some documents in the wiki have not been updated yet, use the --help for the latest manual.

Also, there might still be some bugs, although we have tested it in many rounds. but the program is a huge load now. Hope you can contact us if you find some. Thanks a lot!

BTW, the webserver is also upgrading, I apologize for any inconvenience. 


Best,
Jiayu

**Comment by KennthShang** [comment]
Also, the abovementioned installation will keep your phabox2 in the latest way. We will also continuously updating the channel via anaconda cloud.

**Comment by KennthShang** [comment]
Hi, the v2.1 is available. Please try:

```
conda create -n phabox2 jyshang2::phabox=2.1 -c bioconda -c conda-forge -y

```

Also, please make sure the phabox package is from jyshang2 channel so that all the programs can be up-to-date. The phabox package from bioconda may lag over time.

In addition, the current package is not available via mamba.

Best,
Jiayu
