### ISSUE TITLE
Inconsistency in Results Between PhaBOX/PhaTYP_single.py and phabox2 --task phatyp

### ISSUE THREAD

**Issue by WoCer2019** [KennthShang/PhaBOX#47]
Hi,

I am writing to inquire about discrepancies I have observed between the outputs generated by PhaBOX/PhaTYP_single.py and phabox2 when using the "--task phatyp" option. Despite using identical input files and parameter settings, there are significant inconsistencies in the results produced by these two methods.

Could you please provide insight into what might be causing these differences? Is it due to variations in how each tool processes the data, or could there be other factors at play that I should be aware of?

Additionally, I would like to confirm whether the final results should be considered accurate according to the latest version of phabox2. If so, could you also advise on any specific steps or best practices for ensuring consistency when transitioning from PhaBOX/PhaTYP_single.py to phabox2?

Your guidance on this matter would be greatly appreciated as it is important for us to understand the reliability and consistency of the results for our ongoing research.

Thank you very much for your time and assistance.

WarrenYates

**Comment by KennthShang** [comment]
Hi WarrenYates @WoCer2019 ,

Thanks for using our tools.

The different workflow causes the inconsistency and I list the reasons below for your reference.

As mentioned in the end_to_end task. The program will first run the PhaMer (virus identification) and PhaGCN (taxonomy classification). If the sequences are justified as viral sequences by PhaMer and classified as (prokaryotic viruses) by PhaGCN, then these sequences will be feed into the PhaTYP model to predict the lifestyle. This is because only prokaryotic viruses have such a "lifestyle" definition.

However, If you only call the PhaTYP task, the program will consider all your input sequences directly.

So, it depends on whether you are confident in your input. If your input is definitely prokaryotic viruses, then you can call the PhaTYP directly. Sometimes the previous PhaMer and PhaGCN tasks will lose some data (since no tools can ensure 100% recall with high precision). But if you are not certain about the composition of your inputs, then going for the end-to-end task will lead to more reliable results.

Hope this information will help. Feel free to let me know if you have further questions.

Best,
Jiayu

**Comment by WoCer2019** [comment]
Thank you for your prompt and detailed response.

I appreciate the clarification regarding the different workflows between the end-to-end task and directly calling the PhaTYP task. However, I would like to clarify that in my case, both methods I used were simply invoking the PhaTYP task without involving the preceding PhaMer or PhaGCN steps. Therefore, all input sequences should have been considered directly by the PhaTYP model, which means that the discrepancies observed are unlikely due to differences in workflow or sequence filtering.

Given this situation, it seems more probable that the inconsistencies arise from other factors such as differences in reference databases or changes in the underlying algorithms between the two versions of the tool. Considering these possibilities, could you recommend which version's results should be taken as the standard?

Best regards,

WarrenYates

**Comment by KennthShang** [comment]
Ah, I see. I got your point. 

It seems you are asking for PhaBOX/PhaTYP_single.py and the current available PhaBOX2. 

PhaBOX/PhaTYP_single.py refers to the first version of PhaBOX and we have just upgraded the program to PhaBOX2. We have updated the database with the latest ICTV. So PhaBOX2 version is more reliable. 

The scripts in the current Github are also updated to version 2. You can find the release at: https://github.com/KennthShang/PhaBOX/releases. New updates and WIKI can also be found via:https://github.com/KennthShang/PhaBOX/wiki

Hope you will enjoy the updates and new functions.

Best,
Jiayu

**Comment by WoCer2019** [comment]
Thanks.

WarrenYates

________________________________

**Comment by WoCer2019** [comment]
Thanks.
